"""
bollinger_bands.py — Bollinger Bands mean reversion strategy.
Generated by Claude AI agent as part of agentic project requirements.
"""
import pandas as pd
from strategies.base import Strategy


class BollingerBandsStrategy(Strategy):
    """
    Buy when close price crosses below the lower Bollinger Band.
    Sell when close price crosses above the upper Bollinger Band.
    Hold otherwise.

    Params:
        window (int): Rolling window for SMA and std. Default 20.
        num_std (float): Number of standard deviations for bands. Default 2.0.
    """

    def generate_signals(self, df: pd.DataFrame) -> pd.Series:
        window = self.params.get("window", 20)
        num_std = self.params.get("num_std", 2.0)
        close = df["close"]
        sma = close.rolling(window).mean()
        std = close.rolling(window).std()
        upper = sma + num_std * std
        lower = sma - num_std * std
        signals = pd.Series(0, index=df.index)
        signals[close < lower] = 1
        signals[close > upper] = -1
        return signals


if __name__ == "__main__":
    import sys
    sys.path.insert(0, ".")
    from data.database import load_ohlcv
    df = load_ohlcv("QQQ")
    strategy = BollingerBandsStrategy(params={"window": 20, "num_std": 2.0})
    signals = strategy.generate_signals(df)
    print(signals.value_counts())
    print("Bollinger Bands strategy OK!")